spring:
  application:
    name: ${APP_NAME:cupon}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/coupons_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    url: ${FLYWAY_URL:${DB_URL:jdbc:postgresql://localhost:5432/coupons_db}}
    user: ${FLYWAY_USER:${DB_USERNAME:postgres}}
    password: ${FLYWAY_PASSWORD:${DB_PASSWORD:postgres}}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: never