spring:
  name: cupon
  datasource:
    url: jdbc:postgresql://localhost:5432/coupons_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: never
